#!/bin/bash
# Check if oversize message error is generated by receiver
# and message is accepted correctly.
. ${srcdir:=$(pwd)}/test-framework.sh
export errorlog="error.$LIBRELP_DYN.log"

startup_receiver -m 140 -o "accept" -e $TESTDIR/$errorlog

echo 'Send Message...'
./send -t 127.0.0.1 -p $TESTPORT -m "testmessage1" -d 150 1>>client.err.log 2>&1

stop_receiver
check_output "error.*frame too long.*will still be accepted" $TESTDIR/$errorlog
check_output "^testmessage1012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567$"
terminate
