#!/bin/bash
# Check if oversize message error is generated by receiver
# and message is accepted correctly.
. ${srcdir}/test-framework.sh
startup_receiver -m 140 -o "accept" -e error.out.log

echo 'Send Message...'
./send -t 127.0.0.1 -p $TESTPORT -m "testmessage1" -d 150 1>>client.err.log 2>&1

stop_receiver
check_output "error.*frame too long.*will still be accepted" error.out.log
check_output "^testmessage1012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567$"
terminate
